FIELDS_BY_INDUSTRY = {
    "ecom": {
        "order_item_currency": "P0",
        "order_original_order_number": "P0",
        "product_name": "P0",
        "order_item_delivery_address": "P0",
        "order_item_total_price_paid": "P0",
        "order_item_delivery_type": "P1",
        "brand_name": "P1",
        "seller_name": "P1",
        "order_item_state": "P1",
        "payment_method_name": "P1"
    },
    "payment": {
        "order_original_order_number_raw": "P0",
        "order_item_original_order_number_raw": "P0",
        "order_total_paid": "P0",
        "order_currency": "P0",
        "seller_name": "P0",
        "order_item_currency": "P0",
        "payment_method_name": "P1",
        "order_order_date": "P1",
        "order_item_total_price_paid": "P1"
    },
    "cab": {
        "order_currency": "P0",
        "order_other_fee": "P0",
        "order_total_paid": "P0",
        "order_item_departure_address": "P0",
        "order_item_arrival_address": "P0",
        "order_item_total_price_paid": "P0",
        "seller_name": "P0",
        "order_order_date": "P1",
        "order_original_order_number_raw": "P1",
        "order_promo": "P1",
        "payment_method_name": "P1",
        "order_item_original_order_number_raw": "P1",
        "product_class": "P1"
    },
    "food_delivery": {
        "order_currency": "P0",
        "order_original_order_number_raw": "P0",
        "order_total_paid": "P0",
        "order_item_currency": "P0",
        "order_item_delivery_address": "P0",
        "order_item_original_order_number_raw": "P0",
        "seller_name": "P0",
        "order_item_total_price_paid": "P0",
        "order_order_date": "P1",
        "order_delivery_fee": "P1",
        "payment_method_name": "P1",
        "order_promo": "P1",
        "order_item_delivery_type": "P1"
    },
    "mobile_gaming": {
        "order_original_order_number_raw": "P0",
        "order_total_paid": "P0",
        "product_name": "P0",
        "order_item_total_price_paid": "P0",
        "order_currency": "P0",
        "order_item_billing_address": "P1",
        "order_item_original_order_number_raw": "P0",
        "order_item_currency": "P0",
        "payment_method_name": "P1",
        "order_item_option_1": "P1",
        "seller_name": "P1",
        "order_promo": "P1",
        "order_tax": "P1",
    },
    "gaming": {
        "order_original_order_number_raw": "P0",
        "order_total_paid": "P0",
        "order_total_fees": "P0",
        "product_name": "P0",
        "order_currency": "P0",
        "order_item_billing_address": "P0",
        "order_item_original_order_number_raw": "P0",
        "order_item_currency": "P0",
        "order_item_total_price_paid": "P0",
        "order_order_date": "P1",
        "payment_method_name": "P1",
        "seller_name": "P1"
    }
    ,
    "travel": {
        "order_original_order_number_raw": "P0",
        "order_currency": "P0",
        "seller_name": "P0",
        "order_total_paid": "P0",
        "order_item_original_order_number_raw": "P0",
        "order_item_currency": "P0",
        "order_item_start_date": "P0",
        "order_item_end_date": "P0",
        "payment_method_name": "P1",
        "order_total_fees": "P1",
        "order_nb_of_users": "P1",
        "product_name": "P1",
        "order_item_address": "P1",
        "order_item_departure_address": "P1",
        "order_item_arrival_address": "P1",
        "order_item_departure_date": "P1",
        "order_item_arrival_date": "P1"
    }
}
